/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CuisinesRouteImport } from './routes/cuisines'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ShareRouteImport } from './routes/share'
import { Route as CreatorsIndexRouteImport } from './routes/creators.index'
import { Route as CreatorsHandleRouteImport } from './routes/creators.$handle'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisinesRoute = CuisinesRouteImport.update({
  id: '/cuisines',
  path: '/cuisines',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsIndexRoute = CreatorsIndexRouteImport.update({
  id: '/creators/',
  path: '/creators/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsHandleRoute = CreatorsHandleRouteImport.update({
  id: '/creators/$handle',
  path: '/creators/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/cuisines': typeof CuisinesRoute
  '/dashboard': typeof DashboardRoute
  '/share': typeof ShareRoute
  '/creators/$handle': typeof CreatorsHandleRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/creators/': typeof CreatorsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/cuisines': typeof CuisinesRoute
  '/dashboard': typeof DashboardRoute
  '/share': typeof ShareRoute
  '/creators/$handle': typeof CreatorsHandleRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/creators': typeof CreatorsIndexRoute
  '/journal': typeof JournalIndexRoute
  '/recipes': typeof RecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/cuisines': typeof CuisinesRoute
  '/dashboard': typeof DashboardRoute
  '/share': typeof ShareRoute
  '/creators/$handle': typeof CreatorsHandleRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/creators/': typeof CreatorsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/collections'
    | '/cuisines'
    | '/dashboard'
    | '/share'
    | '/creators/$handle'
    | '/journal/$slug'
    | '/recipes/$slug'
    | '/creators/'
    | '/journal/'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/collections'
    | '/cuisines'
    | '/dashboard'
    | '/share'
    | '/creators/$handle'
    | '/journal/$slug'
    | '/recipes/$slug'
    | '/creators'
    | '/journal'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/collections'
    | '/cuisines'
    | '/dashboard'
    | '/share'
    | '/creators/$handle'
    | '/journal/$slug'
    | '/recipes/$slug'
    | '/creators/'
    | '/journal/'
    | '/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CollectionsRoute: typeof CollectionsRoute
  CuisinesRoute: typeof CuisinesRoute
  DashboardRoute: typeof DashboardRoute
  ShareRoute: typeof ShareRoute
  CreatorsHandleRoute: typeof CreatorsHandleRoute
  JournalSlugRoute: typeof JournalSlugRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
  CreatorsIndexRoute: typeof CreatorsIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisines': {
      id: '/cuisines'
      path: '/cuisines'
      fullPath: '/cuisines'
      preLoaderRoute: typeof CuisinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/': {
      id: '/creators/'
      path: '/creators'
      fullPath: '/creators/'
      preLoaderRoute: typeof CreatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$handle': {
      id: '/creators/$handle'
      path: '/creators/$handle'
      fullPath: '/creators/$handle'
      preLoaderRoute: typeof CreatorsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CollectionsRoute: CollectionsRoute,
  CuisinesRoute: CuisinesRoute,
  DashboardRoute: DashboardRoute,
  ShareRoute: ShareRoute,
  CreatorsHandleRoute: CreatorsHandleRoute,
  JournalSlugRoute: JournalSlugRoute,
  RecipesSlugRoute: RecipesSlugRoute,
  CreatorsIndexRoute: CreatorsIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
